{% set name = "rucio-clients" %}
{% set version = "1.26.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rucio-clients-{{ version }}.tar.gz
  sha256: a504b2bf93e7a1bc1dede72817200331d89c8a7a9257e7f48e0fbbd88fe7640b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dogpile.cache >=0.6.5,<=1.1.1
    - jsonschema >=3.2.0
    - python >=3.6
    - requests <=2.25.0,>=2.20.0
    - six <1.16.0,>=1.12.0
    - tabulate <0.9.0,>=0.8.0
    - urllib3 <=1.26.5,>=1.24.2

test:
  imports:
    - rucio
    - rucio.client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://rucio.cern.ch/
  summary: Rucio Client Lite Package
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bari12
