{% set name = "rucio-clients" %}
{% set version = "1.28.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rucio-clients-{{ version }}.tar.gz
  sha256: c05ab226f265747730d415b19b7b3f9037fdfc8e473a1937369f9f002261a59b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dogpile.cache >=0.6.5,<=1.1.5
    - jsonschema ~=3.2.0
    - python >=3.6
    - requests >=2.20.0,<=2.27.1
    - six >=1.12.0,<=1.16.0
    - tabulate ~=0.8.0
    - urllib3 >=1.24.2,<=1.26.8

test:
  imports:
    - rucio
    - rucio.client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://rucio.cern.ch/
  summary: Rucio Client Lite Package
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bari12
